create table MOVIES
(
  ID           SERIAL PRIMARY KEY,
  NAME_RU      VARCHAR(255) NOT NULL,
  NAME_EN      VARCHAR(255) NOT NULL,
  RELEASE_YEAR INT          NOT NULL,
  DESCRIPTION  VARCHAR      NOT NULL,
  RATING       DECIMAL      NOT NULL,
  PRICE        DECIMAL      NOT NULL,
  PICTURE_PATH  VARCHAR      NOT NULL
);
