UPDATE USERS
SET (PASSWORD, USER_ROLE) =
        ('$2a$08$F5rK18KV86WFOEOtUBXb3Odl53xlm2ww9FnJXHmEloIZyaCAaEo.W', 'ROLE_USER')
WHERE user_name = 'paco';
UPDATE USERS
SET (PASSWORD, USER_ROLE) =
        ('$2a$08$rQLJjrXs7m9JMYXOOJ2EvuJjmI7QXF1EEkGGSvT4OOSVdZGIXnLSC', 'ROLE_USER')
WHERE user_name = 'bricks';
UPDATE USERS
SET (PASSWORD, USER_ROLE) =
        ('$2a$08$6Zh8VHpP7JbDLZmrp4jHdOoNMzY6JZnRh8H7YUTWR6RgFvX4OAGYu', 'ROLE_USER')
WHERE user_name = 'hjkl';
UPDATE USERS
SET (PASSWORD, USER_ROLE) =
        ('$2a$08$7LKpqvWBr1tPsTesyCLdKOFSkxU4et.QwGp0z26rYw.56o938s1x6', 'ROLE_USER')
WHERE user_name = 'exodus';
UPDATE USERS
SET (PASSWORD, USER_ROLE) =
        ('$2a$08$yv2KThOepP9RR1uwvRL7Vuv0MXkZHtwcj31kEUYDUqjMj2OWkB.Ga', 'ROLE_USER')
WHERE user_name = '878787';
UPDATE USERS
SET (PASSWORD, USER_ROLE) =
        ('$2a$08$CK3CbUWC3PS4NAhlThw0j.JtQpet7Eiwi7.peRI9OLVh26NvwB9wa', 'ROLE_USER')
WHERE user_name = 'smart';
UPDATE USERS
SET (PASSWORD, USER_ROLE) =
        ('$2a$08$ap1NA5xjmqND2SCp7JlE.O1RBzgJlKJlk2tNgq./HOtmjZO18g7Ny', 'ROLE_USER')
WHERE user_name = 'beaker';
UPDATE USERS
SET (PASSWORD, USER_ROLE) =
        ('$2a$08$z0xInEFP/Ighzxr3pGGyRevDmFzacJTyItahfYci7xswnC4ry7KYK', 'ROLE_USER')
WHERE user_name = 'pepsi1';
UPDATE USERS
SET (PASSWORD, USER_ROLE) =
        ('$2a$08$Ofysd/l25njZXur3uV6/6OkUQb1S3AXefMaWITC9nNoqx9wCOytRa', 'ROLE_USER')
WHERE user_name = 'tommy';
UPDATE USERS
SET (PASSWORD, USER_ROLE) =
        ('$2a$08$Yo9p/GyEeW2gsUQObZsJrOAI6P5VEaFBUqp8TqXLxu4zoAqfs3P5O', 'ROLE_USER')
WHERE user_name = 'coldbeer';